

[pytest]

addopts  =

    # General options
    -v
    --browser=chromium
    --headed
    --base-url=https://pd.kantimehealth.net/kantime/Login.aspx

    # Reporting options
    --video=retain-on-failure
    #if u want capture video, if its success also
    #--video =on
    --screenshot=only-on-failure
    #if u want capture screenshot, if its success also
    #--screenshot =on
    --alluredir=C:/Pycharm/PythonProject/PythonProject1/PDProjectWithFW/reports/allure-results
    --tracing=retain-on-failure

     # markers
markers =
    sanity
    regression
    datadriven
    end-to-end